"""user add params

Revision ID: 2f8bc0b88e65
Revises: f984ebc4af70
Create Date: 2020-07-14 18:55:35.264066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8bc0b88e65'
down_revision = 'f984ebc4af70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('currencyGold', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('currencySilver', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('energy', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('energyMax', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('exp', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('expNextLevel', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'level')
    op.drop_column('user', 'expNextLevel')
    op.drop_column('user', 'exp')
    op.drop_column('user', 'energyMax')
    op.drop_column('user', 'energy')
    op.drop_column('user', 'currencySilver')
    op.drop_column('user', 'currencyGold')
    # ### end Alembic commands ###
