"""fix table user

Revision ID: 5d8fee213c4a
Revises: 972d82d50e41
Create Date: 2020-07-19 15:20:31.613867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8fee213c4a'
down_revision = '972d82d50e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hero_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hero_type')
    # ### end Alembic commands ###
