"""first

Revision ID: 739ce0dec76e
Revises: 
Create Date: 2020-08-05 17:39:37.999410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739ce0dec76e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_type', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('currencyGold', sa.Integer(), nullable=True),
    sa.Column('currencySilver', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('enemies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('battle_id', sa.Integer(), nullable=True),
    sa.Column('intPoints', sa.Integer(), nullable=True),
    sa.Column('strPoints', sa.Integer(), nullable=True),
    sa.Column('staPoints', sa.Integer(), nullable=True),
    sa.Column('agiPoints', sa.Integer(), nullable=True),
    sa.Column('lucPoints', sa.Integer(), nullable=True),
    sa.Column('perPointsMax', sa.Integer(), nullable=True),
    sa.Column('skillPointsMax', sa.Integer(), nullable=True),
    sa.Column('health', sa.Integer(), nullable=True),
    sa.Column('rage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('battle_id', sa.Integer(), nullable=True),
    sa.Column('intPoints', sa.Integer(), nullable=True),
    sa.Column('strPoints', sa.Integer(), nullable=True),
    sa.Column('staPoints', sa.Integer(), nullable=True),
    sa.Column('agiPoints', sa.Integer(), nullable=True),
    sa.Column('lucPoints', sa.Integer(), nullable=True),
    sa.Column('ergPoints', sa.Integer(), nullable=True),
    sa.Column('perPointsFree', sa.Integer(), nullable=True),
    sa.Column('perPointsMax', sa.Integer(), nullable=True),
    sa.Column('skillPointsFree', sa.Integer(), nullable=True),
    sa.Column('skillPointsMax', sa.Integer(), nullable=True),
    sa.Column('exp', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('health', sa.Integer(), nullable=True),
    sa.Column('rage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero')
    op.drop_table('enemies')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('battle')
    # ### end Alembic commands ###
