"""new table hero

Revision ID: 972d82d50e41
Revises: 
Create Date: 2020-07-19 15:08:35.439452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972d82d50e41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('currencyGold', sa.Integer(), nullable=True),
    sa.Column('currencySilver', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('exp', sa.Integer(), nullable=True),
    sa.Column('expNextLevel', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('energyMax', sa.Integer(), nullable=True),
    sa.Column('perPointsFree', sa.Integer(), nullable=True),
    sa.Column('perPointsMax', sa.Integer(), nullable=True),
    sa.Column('intPoints', sa.Integer(), nullable=True),
    sa.Column('strPoints', sa.Integer(), nullable=True),
    sa.Column('staPoints', sa.Integer(), nullable=True),
    sa.Column('agiPoints', sa.Integer(), nullable=True),
    sa.Column('lucPoints', sa.Integer(), nullable=True),
    sa.Column('skillPointsFree', sa.Integer(), nullable=True),
    sa.Column('skillPointsMax', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
