"""добавлен новый параметр в таблицу враги, отвечающий за получаемый опыт при победе

Revision ID: cb20f5ce09c4
Revises: 9d4b0d506ce8
Create Date: 2020-07-31 17:10:20.153422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb20f5ce09c4'
down_revision = '9d4b0d506ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enemies', sa.Column('exp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enemies', 'exp')
    # ### end Alembic commands ###
