"""add energy points

Revision ID: fe5dc7892632
Revises: 5d8fee213c4a
Create Date: 2020-07-19 16:11:41.925413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5dc7892632'
down_revision = '5d8fee213c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('energyPoints', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hero', 'energyPoints')
    # ### end Alembic commands ###
